name: Distribute

on:
  release:
    types:
      - released

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Compile project
        run: npm run build

      - name: Generate distribution packages
        run: npm run package

      - name: Generate documentation
        run: npm run docgen

      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs

      - uses: actions/upload-artifact@v3
        with:
          name: python
          path: dist/python/*

      - uses: actions/upload-artifact@v3
        with:
          name: js
          path: dist/js/*

      - uses: actions/upload-artifact@v3
        with:
          name: jsii
          path: .jsii

  update-docs:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs

  distribute-python:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: python
          path: dist

      - run: pip install twine

      - run: twine upload dist/*
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

  distribute-js:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: js
          path: dist

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - run: npm publish dist/*
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
